### PR TITLE
feat: add musl build support

### PR DESCRIPTION
**Pull request by rongfengliang**
add musl build support

### CODE REVIEW

**Comment by diogomatsubara** [comment]
Hi @rongfengliang , thanks for your contribution! We require all contributors to signe the Eclipse Contributor Agreement. Could you have it signed so we can consider this PR? Details on how to sign it can be found here: https://api.eclipse.org/git/eca/status/gh/eclipse-zenoh/zenoh-ts/29

**Comment by diogomatsubara** [comment]
@rongfengliang Also take a look at https://github.com/eclipse-zenoh/zenoh-ts/actions/runs/11720545273/job/32646150245#step:2:406, last time we tried to build for those musl targets we got this error and I'm not sure if the addition of the `.cargo/config.toml` will make a difference.

**Comment by rongfengliang** [comment]
@diogomatsubara  I had do some tests with  this config,  also this config is the same as other zenoh sub project config 
https://github.com/eclipse-zenoh/zenoh-backend-filesystem/blob/main/.cargo/config.toml

**Comment by diogomatsubara** [comment]
Changes proposed tested here: https://github.com/eclipse-zenoh/zenoh-ts/actions/runs/11839108359/job/32989870069 and they work to build the musl targets. LGTM

**Review by diogomatsubara — APPROVED** [review]

**Pull request merged**
